import ADMINUI from '@/components/adminui/page';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ADMINUI>
          {children} {/* Render children in the right place */}
        </ADMINUI>
      </body>
    </html>
  );
}
